### ISSUE TITLE
Remove all copyright notices from cs files

### ISSUE THREAD

**Issue by sungam3r** [destructurama/by-ignoring#38]
I see no reason to bloat each file with `Copyright 2017 Serilog Contributors....` . Directory.Build.props includes Copyright and PackageLicenseExpression properties, also repo has LICENSE file.

@nblumhardt OK?

**Comment by nblumhardt** [comment]
In the Serilog org I prefer leaving them, in particular because in combination with the Apache 2.0 terms it means forks/copies must always point back to the original since the license specifies that copyright notices be left intact.

I'd be happy going a different direction here, but I think technically the notices must be left in any files that weren't contributed by either you or me, since the project can only distribute those files under the terms set by their authors, which includes the same consideration mentioned above.

**Comment by sungam3r** [comment]
Does that mean I should add copyright notices in all files where it was missed?
